# this is the file where all constants are located
AUTHOR_PROMPT = "Name des Autors / der Autorin:\n(Nachname, Vorname)"
AUTHOR_LASTNAME_PROMPT = "Nachname des Autors / der Autorin:"
TITLE_PROMPT = "Titel des Werks:"
SUBTITLE_PROMPT = "Untertitel: \n(leer wenn nicht vorhanden)"
EDITION_PROMPT = "Auflage: \n(Zahl eingeben)"
PUBLISHER_PROMPT = "Verlag:"
LOCATION_PROMPT = "Ort:"
YEAR_PROMPT = "Jahr: "
PAGES_PROMPT = "Zitierte Seite(n):"
URL_PROMPT = "URL:"
DOWNDATE_PROMPT = "Herunterladedatum:"