# this is the file where all constants are located
AUTHOR_PROMPT = "Name des Autors: \n (Nachname, Vorname)"
AUTHOR_LASTNAME_PROMPT = "Nachname des Autors:"
TITLE_PROMPT = "Titel des Werks:"
SUBTITLE_PROMPT = "Untertitel: \n (leer lassen wenn keiner vorhanden) "
EDITION_PROMPT = "Auflage: \n (bitte nur eine Zahl eingeben) "
PUBLISHER_PROMPT = "Verlag:"
LOCATION_PROMPT = "Ort:"
YEAR_PROMPT = "Jahr: "
PAGES_PROMPT = "Zitierte Seite(n): \n (bitte ohne \"S.\" eingeben) "
URL_PROMPT = "URL:"
DOWNDATE_PROMPT = "Herunterladedatum:"